spring:
  application:
    name: GreetAPI
  boot:
    admin:
      client:
        url:
        - http://localhost:707

server:
  port: 9091
  

management:
  endpoints:
    web:
      exposure:
        include:
        - '*'
